---
title: "Atlantis parameter set"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Atlantis parameter set}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(atlantio)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

To access the set of parameter included in Atlantis as of version 3-6722, use:

```{r}
# only version 3-6722 is available
atl  <- list_atlantis_parameters(version = "3-6722")
atl$meta[1:3]
atl$parameters[1:2]
```

The table below display the entire set of parameters, note that the followwing abbreviations are used:
- <GRP>: groups abbreviation
- <f>: fisheries
- <coh>: cohort
- <moveGroupCode>: move group code
- <tracerName>: tracer name


```{r, include = FALSE}
dt <- atl$parameters |>
    lapply(
      \(x) data.frame(
        Name = x$name,
        Description = x$description,
        Units = x$units %||% "",
        Type = x$value_type,
        File = x$source_file,
        Dimension = x$dimension
      )
    ) |>
    do.call(what = rbind)

create_param_table <- function(x, height = "500px") {
  x |>
    kableExtra::kbl() |>
    kableExtra::kable_paper() |>
    kableExtra::scroll_box(width = "100%", height = height) |>
    kableExtra::kable_styling(bootstrap_options = "striped")
}
```


# Biology parameters

## Biology

```{r bio, echo = FALSE}
dt  |>
  dplyr::filter(File == "biology_prm")  |>
  dplyr::select(!File) |>
create_param_table()
```

## Groups

```{r grp, echo = FALSE}
dt  |>
  dplyr::filter(File == "groups_csv")  |>
   dplyr::select(!File)  |>
create_param_table()
```


# Physics

## physics.prm

```{r, echo = FALSE}
dt  |>
  dplyr::filter(File == "physics_prm")  |>
   dplyr::select(!File)  |>
create_param_table()
```

## forcing_prm

```{r forc, echo = FALSE}
dt  |>
  dplyr::filter(File == "forcing_prm")  |>
   dplyr::select(!File)  |>
create_param_table()
```


# Harvest

## fisheries.csv

```{r fish, echo = FALSE}
dt  |>
  dplyr::filter(File == "fisheries_csv")  |>
create_param_table("300px")
```

## harvest.prm

```{r harv, echo = FALSE}
dt  |>
  dplyr::filter(File == "harvest_prm")  |>
create_param_table()
```


# Run parameters (run.prm)

```{r run, echo = FALSE}
dt  |>
  dplyr::filter(File == "biology_prm")  |>
create_param_table()
```



# Abbreviations


```{r abbr}
atl$abbreviation
```
